# Generated by Django 5.0.1 on 2024-04-19 18:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CMYKData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lab', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), default=list, null=True, size=3)),
                ('rgb', models.CharField(default='rgb(255, 255, 255)', null=True, verbose_name='RGB')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('illuminant', models.CharField(blank=True, null=True)),
                ('observer', models.CharField(blank=True, null=True)),
                ('filter', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], default='M0', max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tolerance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.JSONField(max_length=20)),
                ('average', models.JSONField(max_length=20)),
                ('maximum', models.JSONField(max_length=20)),
                ('primary_maximum', models.JSONField(max_length=20)),
                ('average_H', models.JSONField(default=dict, max_length=20)),
                ('primary_maximum_H', models.JSONField(default=dict, max_length=20)),
                ('CMYK', models.JSONField(max_length=20)),
                ('secondary', models.JSONField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('paper', models.FloatField(max_length=20)),
                ('average', models.FloatField(max_length=20)),
                ('maximum', models.FloatField(max_length=20)),
                ('primary_maximum', models.FloatField(max_length=20)),
                ('average_H', models.FloatField(max_length=20)),
                ('primary_maximum_H', models.FloatField(max_length=20)),
                ('CMYK', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), default=list, size=4)),
                ('secondary', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), default=list, size=3)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('reference', models.ForeignKey(default='f6e6bbfe-60a7-4a4e-90a9-b75dbbc9a1ef', on_delete=django.db.models.deletion.DO_NOTHING, to='certification.reference')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tolerance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certification.tolerance')),
            ],
        ),
    ]
