# Generated by Django 5.0.1 on 2024-04-19 18:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('calibration_project', models.CharField(max_length=100, verbose_name='Project Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('nominal', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), size=None)),
                ('target', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), size=None)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Target Set Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measured',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('measured', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linearization.calibrationproject')),
                ('color_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linearization.colorset')),
                ('target_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linearization.targetset')),
            ],
        ),
        migrations.AddField(
            model_name='colorset',
            name='target_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linearization.targetset'),
        ),
    ]
