# Generated by Django 5.0.1 on 2024-04-19 18:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('current_device', models.BooleanField(default=False, verbose_name='Current Device')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_serial', models.CharField(max_length=100, verbose_name='Device Serial')),
                ('measurement_mode', models.CharField(max_length=100, verbose_name='Measurement Mode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=100)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('measurement_mode', models.CharField(choices=[('ReflectanceSpot', 'ReflectanceSpot'), ('ReflectanceScan', 'ReflectanceScan'), ('DualReflectanceSpot', 'DualReflectanceSpot'), ('DualReflectanceScan', 'DualReflectanceScan')], default='ReflectanceSpot', max_length=100, verbose_name='Measurement Mode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('density_number', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), default=list, size=4)),
                ('m0', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), blank=True, default=list, null=True, size=None)),
                ('m1', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), blank=True, default=list, null=True, size=None)),
                ('m2', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), blank=True, default=list, null=True, size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device_configuration.requestdata')),
            ],
        ),
    ]
