# Generated by Django 5.0.1 on 2024-04-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('current_device', models.BooleanField(default=False, verbose_name='Current Device')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_serial', models.CharField(max_length=100, verbose_name='Device Serial')),
                ('measurement_mode', models.CharField(max_length=100, verbose_name='Measurement Mode')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
